// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: ClientServer_TokenService.proto

package Tok_Service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define the message format for a token.
type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Low  uint64 `protobuf:"varint,3,opt,name=low,proto3" json:"low,omitempty"`
	Mid  uint64 `protobuf:"varint,4,opt,name=mid,proto3" json:"mid,omitempty"`
	High uint64 `protobuf:"varint,5,opt,name=high,proto3" json:"high,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientServer_TokenService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_ClientServer_TokenService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_ClientServer_TokenService_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Token) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Token) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Token) GetMid() uint64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *Token) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

type CreateTokResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateMessage string `protobuf:"bytes,1,opt,name=create_message,json=createMessage,proto3" json:"create_message,omitempty"`
}

func (x *CreateTokResponse) Reset() {
	*x = CreateTokResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientServer_TokenService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTokResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokResponse) ProtoMessage() {}

func (x *CreateTokResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ClientServer_TokenService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokResponse.ProtoReflect.Descriptor instead.
func (*CreateTokResponse) Descriptor() ([]byte, []int) {
	return file_ClientServer_TokenService_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTokResponse) GetCreateMessage() string {
	if x != nil {
		return x.CreateMessage
	}
	return ""
}

type DropTokResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DropMessage string `protobuf:"bytes,1,opt,name=drop_message,json=dropMessage,proto3" json:"drop_message,omitempty"`
}

func (x *DropTokResponse) Reset() {
	*x = DropTokResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientServer_TokenService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropTokResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTokResponse) ProtoMessage() {}

func (x *DropTokResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ClientServer_TokenService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTokResponse.ProtoReflect.Descriptor instead.
func (*DropTokResponse) Descriptor() ([]byte, []int) {
	return file_ClientServer_TokenService_proto_rawDescGZIP(), []int{2}
}

func (x *DropTokResponse) GetDropMessage() string {
	if x != nil {
		return x.DropMessage
	}
	return ""
}

type WriteTokResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WriteMessage string `protobuf:"bytes,1,opt,name=write_message,json=writeMessage,proto3" json:"write_message,omitempty"`
}

func (x *WriteTokResponse) Reset() {
	*x = WriteTokResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientServer_TokenService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteTokResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTokResponse) ProtoMessage() {}

func (x *WriteTokResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ClientServer_TokenService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTokResponse.ProtoReflect.Descriptor instead.
func (*WriteTokResponse) Descriptor() ([]byte, []int) {
	return file_ClientServer_TokenService_proto_rawDescGZIP(), []int{3}
}

func (x *WriteTokResponse) GetWriteMessage() string {
	if x != nil {
		return x.WriteMessage
	}
	return ""
}

type ReadTokResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReadMessage string `protobuf:"bytes,1,opt,name=read_message,json=readMessage,proto3" json:"read_message,omitempty"`
}

func (x *ReadTokResponse) Reset() {
	*x = ReadTokResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientServer_TokenService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTokResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTokResponse) ProtoMessage() {}

func (x *ReadTokResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ClientServer_TokenService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTokResponse.ProtoReflect.Descriptor instead.
func (*ReadTokResponse) Descriptor() ([]byte, []int) {
	return file_ClientServer_TokenService_proto_rawDescGZIP(), []int{4}
}

func (x *ReadTokResponse) GetReadMessage() string {
	if x != nil {
		return x.ReadMessage
	}
	return ""
}

var File_ClientServer_TokenService_proto protoreflect.FileDescriptor

var file_ClientServer_TokenService_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x63, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6c, 0x6f, 0x77,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6d,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x22, 0x3a, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x34, 0x0a, 0x0f, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x6f, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x72, 0x6f, 0x70, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x72, 0x6f,
	0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x10, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x54, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x34, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x61, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xb0, 0x01, 0x0a, 0x0c, 0x6d, 0x79, 0x74, 0x6f,
	0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x6f, 0x6b, 0x12, 0x06, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x12, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x07, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x6f, 0x6b, 0x12, 0x06,
	0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x10, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x6f, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x08, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x12, 0x06, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x11,
	0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x6b, 0x12, 0x06,
	0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x10, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f,
	0x54, 0x6f, 0x6b, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ClientServer_TokenService_proto_rawDescOnce sync.Once
	file_ClientServer_TokenService_proto_rawDescData = file_ClientServer_TokenService_proto_rawDesc
)

func file_ClientServer_TokenService_proto_rawDescGZIP() []byte {
	file_ClientServer_TokenService_proto_rawDescOnce.Do(func() {
		file_ClientServer_TokenService_proto_rawDescData = protoimpl.X.CompressGZIP(file_ClientServer_TokenService_proto_rawDescData)
	})
	return file_ClientServer_TokenService_proto_rawDescData
}

var file_ClientServer_TokenService_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ClientServer_TokenService_proto_goTypes = []interface{}{
	(*Token)(nil),             // 0: Token
	(*CreateTokResponse)(nil), // 1: CreateTokResponse
	(*DropTokResponse)(nil),   // 2: DropTokResponse
	(*WriteTokResponse)(nil),  // 3: WriteTokResponse
	(*ReadTokResponse)(nil),   // 4: ReadTokResponse
}
var file_ClientServer_TokenService_proto_depIdxs = []int32{
	0, // 0: mytokService.CreateTok:input_type -> Token
	0, // 1: mytokService.DropTok:input_type -> Token
	0, // 2: mytokService.WriteTok:input_type -> Token
	0, // 3: mytokService.ReadTok:input_type -> Token
	1, // 4: mytokService.CreateTok:output_type -> CreateTokResponse
	2, // 5: mytokService.DropTok:output_type -> DropTokResponse
	3, // 6: mytokService.WriteTok:output_type -> WriteTokResponse
	4, // 7: mytokService.ReadTok:output_type -> ReadTokResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ClientServer_TokenService_proto_init() }
func file_ClientServer_TokenService_proto_init() {
	if File_ClientServer_TokenService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ClientServer_TokenService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientServer_TokenService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTokResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientServer_TokenService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropTokResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientServer_TokenService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteTokResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientServer_TokenService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTokResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ClientServer_TokenService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ClientServer_TokenService_proto_goTypes,
		DependencyIndexes: file_ClientServer_TokenService_proto_depIdxs,
		MessageInfos:      file_ClientServer_TokenService_proto_msgTypes,
	}.Build()
	File_ClientServer_TokenService_proto = out.File
	file_ClientServer_TokenService_proto_rawDesc = nil
	file_ClientServer_TokenService_proto_goTypes = nil
	file_ClientServer_TokenService_proto_depIdxs = nil
}
