// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: proj_proto.proto

package Rep

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenManagerClient is the client API for TokenManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenManagerClient interface {
	ReplScheme(ctx context.Context, in *ReplSchemeRequest, opts ...grpc.CallOption) (*ReplSchemeResponse, error)
	ReadToken(ctx context.Context, in *ReadTokenRequest, opts ...grpc.CallOption) (*ReadTokenResponse, error)
	WriteToken(ctx context.Context, in *WriteTokenRequest, opts ...grpc.CallOption) (*WriteTokenResponse, error)
}

type tokenManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenManagerClient(cc grpc.ClientConnInterface) TokenManagerClient {
	return &tokenManagerClient{cc}
}

func (c *tokenManagerClient) ReplScheme(ctx context.Context, in *ReplSchemeRequest, opts ...grpc.CallOption) (*ReplSchemeResponse, error) {
	out := new(ReplSchemeResponse)
	err := c.cc.Invoke(ctx, "/TokenManager/ReplScheme", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenManagerClient) ReadToken(ctx context.Context, in *ReadTokenRequest, opts ...grpc.CallOption) (*ReadTokenResponse, error) {
	out := new(ReadTokenResponse)
	err := c.cc.Invoke(ctx, "/TokenManager/ReadToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenManagerClient) WriteToken(ctx context.Context, in *WriteTokenRequest, opts ...grpc.CallOption) (*WriteTokenResponse, error) {
	out := new(WriteTokenResponse)
	err := c.cc.Invoke(ctx, "/TokenManager/WriteToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenManagerServer is the server API for TokenManager service.
// All implementations must embed UnimplementedTokenManagerServer
// for forward compatibility
type TokenManagerServer interface {
	ReplScheme(context.Context, *ReplSchemeRequest) (*ReplSchemeResponse, error)
	ReadToken(context.Context, *ReadTokenRequest) (*ReadTokenResponse, error)
	WriteToken(context.Context, *WriteTokenRequest) (*WriteTokenResponse, error)
	mustEmbedUnimplementedTokenManagerServer()
}

// UnimplementedTokenManagerServer must be embedded to have forward compatible implementations.
type UnimplementedTokenManagerServer struct {
}

func (UnimplementedTokenManagerServer) ReplScheme(context.Context, *ReplSchemeRequest) (*ReplSchemeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplScheme not implemented")
}
func (UnimplementedTokenManagerServer) ReadToken(context.Context, *ReadTokenRequest) (*ReadTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadToken not implemented")
}
func (UnimplementedTokenManagerServer) WriteToken(context.Context, *WriteTokenRequest) (*WriteTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteToken not implemented")
}
func (UnimplementedTokenManagerServer) mustEmbedUnimplementedTokenManagerServer() {}

// UnsafeTokenManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenManagerServer will
// result in compilation errors.
type UnsafeTokenManagerServer interface {
	mustEmbedUnimplementedTokenManagerServer()
}

func RegisterTokenManagerServer(s grpc.ServiceRegistrar, srv TokenManagerServer) {
	s.RegisterService(&TokenManager_ServiceDesc, srv)
}

func _TokenManager_ReplScheme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplSchemeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenManagerServer).ReplScheme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TokenManager/ReplScheme",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenManagerServer).ReplScheme(ctx, req.(*ReplSchemeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenManager_ReadToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenManagerServer).ReadToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TokenManager/ReadToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenManagerServer).ReadToken(ctx, req.(*ReadTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenManager_WriteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenManagerServer).WriteToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TokenManager/WriteToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenManagerServer).WriteToken(ctx, req.(*WriteTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenManager_ServiceDesc is the grpc.ServiceDesc for TokenManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TokenManager",
	HandlerType: (*TokenManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplScheme",
			Handler:    _TokenManager_ReplScheme_Handler,
		},
		{
			MethodName: "ReadToken",
			Handler:    _TokenManager_ReadToken_Handler,
		},
		{
			MethodName: "WriteToken",
			Handler:    _TokenManager_WriteToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proj_proto.proto",
}
